git add package.json package-lock.json index.html; git commit -m "chore: initialize project with npm packages and entry point"
git add vite.config.ts tsconfig.json tsconfig.node.json tsconfig.app.json; git commit -m "chore: configure vite and typescript setup"
git add tailwind.config.js postcss.config.js; git commit -m "chore: add tailwindcss and postcss configurations"
git add eslint.config.js; git commit -m "chore: configure eslint for code quality"
git add .gitignore .env; git commit -m "chore: setup environment variables and gitignore"
git add src/main.tsx src/App.tsx; git commit -m "feat: setup react root and main app component"
git add src/index.css src/App.css; git commit -m "style: apply global styles and variables"
git add public/ src/assets/ *.svg; git commit -m "chore: add static assets and icons"
git add src/api/axios.ts; git commit -m "feat: configure axios interceptors for api calls"
git add src/api/firebase.ts; git commit -m "feat: setup firebase initialization and services"
git add src/store/authStore.ts; git commit -m "feat: implement zustand store for authentication"
git add src/context/authContext.ts; git commit -m "feat: define typescript interfaces for auth"
git add src/context/AuthContext.tsx; git commit -m "feat: create authentication context provider"
git add src/context/authSync.ts src/context/useAuth.ts; git commit -m "feat: implement auth state synchronization hooks"
git add src/components/Navbar.tsx; git commit -m "feat: build responsive navigation bar"
git add src/components/Footer.tsx; git commit -m "feat: build website footer component"
git add src/components/ProductCard.tsx; git commit -m "feat: create reusable product card component"
git add src/components/AiChatbot.tsx; git commit -m "feat: integrate ai chatbot component"
git add src/components/ProtectedRoute.tsx; git commit -m "feat: add route protection for authenticated users"
git add src/components/GenericPage.tsx; git commit -m "feat: create generic layout wrappers"
git add src/pages/Home.tsx; git commit -m "feat: develop landing page with hero and features"
git add src/pages/Explore.tsx; git commit -m "feat: implement explore page with filtering and dynamic data"
git add src/pages/ProductDetails.tsx; git commit -m "feat: create dynamic product details view"
git add src/pages/Login.tsx; git commit -m "feat: build user login interface"
git add src/pages/Register.tsx; git commit -m "feat: build user registration flow"
git add src/pages/Dashboard.tsx; git commit -m "feat: develop secure user dashboard"
git add src/pages/About.tsx src/pages/Contact.tsx; git commit -m "feat: add static informational pages"
git add seed_products.js fix_escapes.js; git commit -m "chore: add database seeding utilities"
git add .; git commit -m "fix: minor adjustments and remaining cleanups"
git push origin main -f